library(shiny)
library(markdown)
library(readstata13)
library(tidyverse)
library(ggpubr)
library(shinycssloaders)
library(highcharter)
library(magrittr)
library(cowplot)
`%out%` = Negate(`%in%`)
runApp(launch.browser = T)